apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - image: registry.digitalocean.com/do-challenge-registry/simple-webapp:0.1
          name: simple-app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always